import Link from "next/link";
import { APP_NAME } from "@/lib/constants";
import { cn } from "@/lib/utils";

/**
 * Brand mark — the single source of truth for the logo.
 *
 * **SkillGauge** is drawn as a dial: a 220° arc, a needle reading 50° and a
 * hub. It uses the same 64-unit design grid as `src/app/icon.svg` (identical
 * path data), so the favicon, the rasterised PNG/ICO assets and this inline
 * SVG always agree. The artwork is regenerated by
 * `scripts/generate-brand-assets.mjs` — keep the three in sync.
 */
export function BrandMark({ className }: { className?: string }) {
  return (
    <span
      className={cn(
        "flex size-9 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-primary-500 via-primary-600 to-violet-600 text-white shadow-glow",
        className,
      )}
      aria-hidden="true"
    >
      <svg viewBox="0 0 64 64" fill="none" className="size-5">
        {/* dial arc */}
        <path
          d="M16.03 43.81 A17 17 0 1 1 47.97 43.81"
          stroke="currentColor"
          strokeWidth="5.2"
          strokeLinecap="round"
        />
        {/* needle */}
        <path
          d="M32 38 41.64 26.51"
          stroke="#a5f3fc"
          strokeWidth="5.2"
          strokeLinecap="round"
        />
        {/* hub */}
        <circle cx="32" cy="38" r="4" fill="currentColor" />
      </svg>
    </span>
  );
}

/**
 * Mark + wordmark, linked to the given route.
 *
 * `size` scales both the tile and the label so the same lockup works in the
 * marketing header, the dashboard sidebar and the auth screens.
 */
export function BrandLogo({
  href = "/",
  size = "md",
  className,
  labelClassName,
}: {
  href?: string;
  size?: "sm" | "md" | "lg";
  className?: string;
  labelClassName?: string;
}) {
  const markSize = size === "sm" ? "size-8" : size === "lg" ? "size-11" : "size-9";
  const textSize = size === "sm" ? "text-sm" : size === "lg" ? "text-xl" : "text-base";

  return (
    <Link
      href={href}
      className={cn("flex items-center gap-2.5", className)}
      aria-label={`${APP_NAME} home`}
    >
      <BrandMark className={markSize} />
      <span
        className={cn(
          "font-semibold tracking-tight text-foreground",
          textSize,
          labelClassName,
        )}
      >
        {APP_NAME}
      </span>
    </Link>
  );
}

export default BrandLogo;
